### ISSUE TITLE
入力したキーの情報をArduinoUNOに送りたい

### ISSUE THREAD

**Issue by drinkBr** [tomoswifty/ros2serial_arduino#2]
質問です。

リンク先のキー入力用ノードからserial_send_nodeを介してArduinoUNOへのシリアル通信を試みています。Arduinoへの通信はRXのランプの点滅から確認できていますが，if文等で受け取ったデータによる条件分岐が出来ていません。直接的な質問とは離れてしまいますが，是非アドバイスをよろしくお願いします。
https://github.com/nek009/key_event

変更点及びArduinoのプログラムは以下の通りです。
<serial_send_node.cpp>
#include"key_event_nodes/key_hit_event_node.hpp"および#include"key_event_msgs/msg/key_event.hpp"の追加
これに伴い~/ros2serial_arduino/include/ros2serial_arduino/内にkey_hit_event_node.hppを追加(include以降は新規作成)key_event_msgs::msg::KeyEvent
19行目　subscription_ = this->create_subscription<key_event_msgs::msg::KeyEvent>(
"key_hit_event", 10, std::bind(&MySubscriber::topic_callback, this, 1));
29行目　%lf から%d　msg->linear.xからmsg->key
33行目　 bytes_written = snprintf(buf, sizeof(buf), "%7.3d\n", msg->key);
56行目　rclcpp::Subscription<key_event_msgs::msg::KeyEvent>::SharedPtr subscription;
78行目　char device_name[] = "/dev/ttyACM0"

KERNEL=="ttyACM0", ATTRS{idVendor}=="2341", ATTRS{idProduct}=="0043", MODE:="0666"
<CMakeLists.txt>
find_package(key_event_nodes REQUIRED)
find_package(key_event_msgs REQUIRED)
ament_target_dependencies(${target} "rclcpp" "std_msgs" "key_event_nodes" "key_event_msgs")

<Arduinoプログラム>
#include <Arduino.h>
String key;//keyがString(文字列)
int i;

void setup(){
Serial.begin( 115200 );
pinMode(2, OUTPUT);
}

void loop(){
if(Serial.available() > 0){
key = Serial.readString();
// key = Serial.readStringUntil('\n');

i = key.toInt();

//k入力時を想定
 if (key == 107){
   digitalWrite(2, LOW);}
 else {
   digitalWrite(2, HIGH);}
}
// if (i > 1){
// digitalWrite(2, HIGH);
// }
// else {
// //digitalWrite(2, LOW);
// }
}

**Comment by tomoswifty** [comment]
返信遅れてしまいました．解決しましたか？

Arduinoで受信したシリアルのデータを確認してください．
keyの中に代入された文字列がkではないことが，if文で分岐できない原因と思います．

**Comment by drinkBr** [comment]
tomoswifty様

ご返信ありがとうございます。すでに解決いたしました。
前のスレッドから親身に相談に乗っていただきありがとうございました。

**Comment by Minaygt** [comment]
こんにちは. ポートの名前を常に更新する必要があります。 ` sudo ln-s/dev/ttyacm0/dev/arduino-mega`
私はこのコマンドを使ってそれを変更しています。 しかし、私が中断したとき、私はエラーを取得します。 これを永久に解決するにはどうすればよいですか？ 事前に感謝します。
![Screenshot from 2024-11-04 15-50-59](https://github.com/user-attachments/assets/6d12a743-2525-4006-bdf4-63282ef94681)
